name: $(major).$(minor).$(revision)$(Rev:.r)
trigger:
- main
- develop

variables:
  solutionFile: 'Gibraltar.PostHog.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  group: code-signing
  major: 1
  minor: 0
  revision: 1
  fileVersion: '$(Build.BuildNumber)'

jobs:
- job: build
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: DownloadSecureFile@1
    name: loupeAgentSigningKey
    inputs:
      secureFile: 'GibraltarSoftwareCCC.pfx'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.sln'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.sln'
   
  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      includesymbols: true
      packagesToPack: 'src/Gibraltar.PostHog/Gibraltar.PostHog.csproj'
      packDirectory: '$(Build.ArtifactStagingDirectory)/packages'
      verbosityPack: 'Minimal'

  - task: NuGetCommand@2
    displayName: 'Sign NuGet Packages'  
    inputs:
      command: 'custom'
      arguments: sign $(Build.ArtifactStagingDirectory)\packages\*.nupkg -CertificatePath $(Agent.TempDirectory)/GibraltarSoftwareCCC.pfx -CertificatePassword $(codeSigningCertPassword) -Timestamper http://timestamp.comodoca.com -Verbosity detailed

  - task: NuGetCommand@2
    displayName: 'Sign NuGet Symbol Packages'  
    inputs:
      command: 'custom'
      arguments: sign $(Build.ArtifactStagingDirectory)\packages\*.snupkg -CertificatePath $(Agent.TempDirectory)/GibraltarSoftwareCCC.pfx -CertificatePassword $(codeSigningCertPassword) -Timestamper http://timestamp.comodoca.com -Verbosity detailed

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/packages'
      artifactName: packages