name: $(major).$(minor).$(revision)$(Rev:.r)
trigger:
- main
- develop

variables:
  agentSolution: 'Gibraltar.PostHog.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  group: code-signing
  major: 1
  minor: 0
  revision: 0
  fileVersion: '$(Build.BuildNumber)'

jobs:
- job: build
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: DownloadSecureFile@1
    name: loupeAgentSigningKey
    inputs:
      secureFile: 'GibraltarSoftwareCCC.pfx'

  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(agentSolution)'
  
  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '**/*.sln'
      arguments: '--configuration $(buildConfiguration)'
  
  - task: DotNetCoreCLI@2
    displayName: 'Pack'
    inputs:
      command: 'pack'
      packagesToPack: 'Gibraltar.PostHog/Gibraltar.PostHog.csproj'
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'Build.BuildNumber'
      arguments: '--output $(Build.ArtifactStagingDirectory)/packages'

  - task: NuGetCommand@2
    displayName: 'Sign NuGet Packages'  
    inputs:
      command: 'custom'
      arguments: sign $(Build.ArtifactStagingDirectory)\packages\*.nupkg -CertificatePath $(Agent.TempDirectory)/GibraltarSoftwareCCC.pfx -CertificatePassword $(codeSigningCertPassword) -Timestamper http://timestamp.comodoca.com -Verbosity detailed

  - task: NuGetCommand@2
    displayName: 'Sign NuGet Symbol Packages'  
    inputs:
      command: 'custom'
      arguments: sign $(Build.ArtifactStagingDirectory)\packages\*.snupkg -CertificatePath $(Agent.TempDirectory)/GibraltarSoftwareCCC.pfx -CertificatePassword $(codeSigningCertPassword) -Timestamper http://timestamp.comodoca.com -Verbosity detailed

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/packages'
      artifactName: packages