trigger:
- main
- develop

variables:
  agentSolution: 'Gibraltar.PostHog.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  major: 1
  minor: 0
  revision: 0
  fileVersion: '$(Build.BuildNumber)'

jobs:
- job: build
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: gitversion/setup@0
    displayName: Setup GitVersion
    inputs:
      versionSpec: '5.x'

  - task: gitversion/execute@0
    displayName: Determine Version
    inputs:
      useConfigFile: True
      configFilePath: './GitVersion.yaml'

  - task: DownloadSecureFile@1
    name: loupeAgentSigningKey
    inputs:
      secureFile: 'loupe.agent.snk'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Agent.TempDirectory)'
      Contents: 'loupe.agent.snk'
      TargetFolder: '$(Build.SourcesDirectory)'

  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(agentSolution)'

  - task: VSBuild@1
    inputs:
      solution: '$(agentSolution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      msbuildArgs: '/p:CustomVersion=$(GitVersion.MajorMinorPatch) /p:CustomInformationalVersion=$(GitVersion.MajorMinorPatch) /p:PackageVersion=$(GitVersion.NuGetVersion)'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/src'
      contents: '**/*.nupkg'
      flattenFolders: true
      targetFolder: '$(Build.ArtifactStagingDirectory)/packages'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/packages'
      artifactName: packages